### ISSUE TITLE
Does not work with latest knex

### ISSUE THREAD

**Issue by m-salamon** [cannblw/knex-paginator#6]
I tried it and It works with knex   `0.15.2`.
But it does not work with the latest knex update `0.16.3`
Please take a look...

Thanks

**Comment by cannblw** [comment]
Hi, thank you for submitting the issue.

I have looked at the changes from 0.15.2 to 0.16.3 and there are quite a few.
What error are you getting using it with 0.16.3?

**Comment by m-salamon** [comment]
I dont remeber the exact error, put it was an overall error like can't `.paginate()` to query

**Comment by GustavoRochaSantos** [comment]
Is this error:
(node:19832) UnhandledPromiseRejectionWarning: TypeError: knex(...).paginate(...) is not a function

**Comment by felixmosh** [comment]
I suspect that it is related to the fact that this lib requires `knex: ""` in the package.json, when I install it, it makes an additional knex inside the `node_modules` of this lib, therefore, the lib modifies the wrong instance.
Just to verify it, I've copy the code to a file in my project, and it works.

**Comment by siberiadev** [comment]
Yeah, I tryed to use it with express + Nuxt. Same as **felixmosh** I found that knex-pagination has it own node_modules folder.

**Comment by siberiadev** [comment]
I delete everything from knex-paginator module (/node_modules/knex-paginator) except lib folder and package.json and it works.
Just add this string before all code in DB query file:
```
const knex = require('./knex.js');
const setupPaginator = require('knex-paginator');
setupPaginator(knex);
```

and my knex.js file is below:
```
const environment = process.env.ENVIRONMENT || 'development'
const config = require('../knexfile.js')[environment];
const knex = require('knex')(config)

module.exports = knex;
```

**Comment by ksorensen76** [comment]
Seeing the same issue. Simply deleting the ./node_modules/knex-paginator/node_modules directory resolves the issue.

knex: 0.17.6
knex-paginator: 1.3.1

**Comment by alinoaimi** [comment]
I fixed the issue and submitted a pull request,
https://github.com/cannblw/knex-paginator/pull/12

the lib folder in knex has recently been renamed to src, and knex-paginator is calling knex query builder using the old path
KnexQueryBuilder = require('knex/lib/query/builder');
simply changing lib to src will fix the issue.

**Comment by cannblw** [comment]
Thank you @el7r for the pull request. I have reviewed and it looks great, I'm going to merge it.

By the way, deleting anything from `node_modules` is not the best idea. It may work for you, but it will break for everyone else working on your project (in case you are working with other devs) or if you clean the repository. You are also interfering with the way `npm` works: the `node_modules` directory is autogenerated.

P.S.: I don't recommend using this library in a production environment. I don't have much time to maintain it and it's very dependent on the version of Knex that you are using because it modifies the prototype of the Knex's query builder. It's better to have a custom solution on your projects.

For this module to be successful, there should be different versions for every version of Knex, or at least for every major version. At this point, it might be better to submit a PR to [Knex's repository](https://github.com/tgriesser/knex).

Thank you for understanding.

**Comment by ziyaddin** [comment]
@cannblw is it possible to give maintainership to anyone so that the project keeps progressing?

**Comment by march08** [comment]
Can we move knex to peer?
